#!/bin/bash

IGNORE="deploy-to-system README"

if [ ! -d "$HOME/.dotfiles/private" ]; then
	echo "Error: You need to have the private files in $HOME/.dotfiles/private"
	exit 1;
fi

if [ ! -d "$HOME/.dotfiles/public" ]; then
	echo "Error: You need to have the private files in $HOME/.dotfiles/public"
	exit 1;
fi

SCRIPT_PATH=$(dirname $0)
for obj in `dirname $0`/*; do
	if [[ $IGNORE =~ $(basename $obj) ]]; then continue; fi
	ln -sf $HOME/.dotfiles/public/$(basename $obj) $HOME/.`basename $obj`
done

ln -sf $HOME/.dotfiles/private/ssh/config $HOME/.ssh/config

mkdir -p $HOME/.vim/{backup,tmp}
