#!/bin/bash

echo "Press enter to deploy `dirname $0` to $HOME"
echo -n "Type ctrl-c to abort "
read

# Deploy normal files
for obj in `dirname $0`/*; do
	if [[ $obj =~ deploy-to-system ]]; then continue; fi
	if [[ $obj =~ README ]]; then continue; fi
	if [[ $obj =~ secret ]]; then continue; fi
	ln -s $obj $HOME/.`basename $obj`
done

# Deploy special files
echo ln -s $HOME/.dotfiles/secret/ssh/config $HOME/.ssh/config
