---

- hosts: all
  sudo: yes
  vars:
    debs:
    - { url: "https://dl.bintray.com/mitchellh/vagrant/vagrant_1.5.2_x86_64.deb", name: "vagrant_1.5.2_x86_64.deb" }
  tasks:
  - name: Update the systems packages
    apt: upgrade=dist update_cache=yes
  - name: Install software from repo
    apt: pkg={{ item }} state=present
    with_items:
    - vim
    - mercurial
    - git
    - terminator
    - synapse
    - chromium-browser
  - name: Download debs
    get_url: url={{ item.url }} dest=/tmp/{{ item.name }}
    with_items: debs
  - name: Install debs
    command: dpkg -iE /tmp/{{ item.name }}
    with_items: debs
