---

- hosts: all
  sudo: yes
  vars:
    debs:
    - { 
        url: "https://dl.bintray.com/mitchellh/vagrant/vagrant_1.5.2_x86_64.deb", 
        name: "vagrant_1.5.2_x86_64.deb",
        sha256sum: "bd20d89df7e33984614092b25864b530d4b73d4db1d04eab396f0457c184b6d7"
      }
    packages:
    - { 
        url: "https://dl.bintray.com/mitchellh/packer/0.5.2_linux_amd64.zip", 
        type: "zip", 
        name: "packer_0.5.2_linux_amd64.zip", 
        sha256sum: "813f856a3d326d2a65f561edac8050d981f93ea51da03b0fb6b3d72010a5fc96"
      }
  tasks:
  - name: Update the systems packages
    apt: upgrade=dist update_cache=yes
  - name: Install software from repo
    apt: pkg={{ item }} state=present
    with_items:
    - vim
    - mercurial
    - git
    - terminator
    - synapse
    - chromium-browser
    - virtualbox-nonfree
    - curl
    - sshpass
  - name: Download debs
    get_url: url={{ item.url }} dest=/tmp/{{ item.name }} sha256sum="{{ item.sha256sum }}"
    with_items: debs
  - name: Download packages
    get_url: url={{ item.url }} dest=/tmp/{{ item.name }} sha256sum="{{ item.sha256sum }}"
    with_items: packages
  - name: Install debs
    command: dpkg -iE /tmp/{{ item.name }}
    with_items: debs
