---

- name: Update inventory
  hosts: localhost
  connection: local
  tasks:
    - name: Place our host in a group with our hostname
      add_host:
        group: "{{ ansible_hostname }}"
        name: "127.0.0.1"

- name: Install packages on all systems
  hosts: all
  become: yes
  tasks:
    - include: install/github-hub.yml

    - name: Install misc software
      apt:
        name:
          - neovim
          - chromium-browser
          - curl
          - ctags
          - silversearcher-ag
          - tig
          - yamllint
          - make
          - tree
          - pavucontrol
          - whois
          - gnome-mpv
          - tilix
          - dconf-editor
          - hub
          - flatpak

    - name: Install classic snaps
      snap:
        name: "{{ item }}"
        classic: yes
      loop:
        - code
        - snapcraft

    - name: Add flathub repo
      flatpak_remote:
        name: flathub
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Personal Workstation and Laptop
  hosts:
    - narsil
    - ringil
    - glamdring
  tasks:
    - name: Install misc software
      apt:
        name:
          - cmake
          - heimdal-clients
          - docker.io

- name: Tweaks for my T490
  hosts:
    - glamdring

  tasks:
    - name: Configure thinkpad_acpi kernel module
      copy:
        content: "options thinkpad_acpi fan_control=1\n"
        dest: /etc/modprobe.d/thinkfan.conf
      register: reboot_now

    - assert:
        that:
          - reboot_now is not changed
        fail_msg: "Please reboot the system now, and run this again!"

    - name: Install packages
      apt:
        name:
          - thinkfan
          - nvme-cli

    - name: Deploy thinkfan-detect
      copy:
        src: files/thinkfan-detect
        dest: /usr/local/bin/thinkfan-detect
        mode: 0755

    - name: Deploy tpthermals
      copy:
        src: files/tpthermals.sh
        dest: /usr/local/bin/tpthermals
        mode: 0755

    - name: Deploy tpthermals unitfile
      copy:
        src: files/tpthermal.service
        dest: /etc/systemd/system/tpthermal.service
        mode: 0755

    - name: Make ovverides directory for systemd unit
      file:
        path: /etc/systemd/system/thinkfan.service.d
        state: directory

    - name: Add pre-script to thinkfan unitfile
      copy:
        content: |
          [Service]
          ExecStartPre=/usr/local/bin/thinkfan-detect
          Restart=on-failure
          RestartSec=60s
        dest: /etc/systemd/system/thinkfan.service.d/detect.conf
      register: reload_systemd

    - name: Reload systemd and start services
      systemd:
        daemon_reload: yes
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - thinkfan
        - tpthermal

- name: "Configure all systems (with your user)"
  hosts: all
  become: no
  user: "{{ ansible_env.USER }}"
  tasks:
    - include: configure/vim_plugins.yml
    - include: configure/dotfiles.yml

    - name: "Make sure we have ~/bin"
      file:
        path: "~/bin"
        state: directory
