---

- name: Update inventory
  hosts: localhost
  connection: local
  tasks:
    - name: Place our host in a group with our hostname
      add_host:
        group: "{{ ansible_hostname }}"
        name: "127.0.0.1"

- name: Install packages on all systems
  hosts: all
  become: yes
  tasks:
    - include: install/github-hub.yml

    - name: Install misc software
      apt:
        name:
          - neovim
          - chromium-browser
          - curl
          - ctags
          - silversearcher-ag
          - tig
          - python-flake8
          - yamllint
          - make
          - tree
          - pavucontrol
          - whois
          - gnome-mpv
          - tilix
          - dconf-editor
          - hub

- name: Personal Workstation and Laptop
  hosts:
    - narsil
    - ringil
    - glamdring
  tasks:
    - name: Install misc software
      apt:
        name:
          - cmake
          - heimdal-clients

- name: "Configure all systems (with your user)"
  hosts: all
  become: no
  user: "{{ ansible_env.USER }}"
  tasks:
    - include: configure/vim_plugins.yml
    - include: configure/dotfiles.yml

    - name: "Make sure we have ~/bin"
      file:
        path: "~/bin"
        state: directory
