#!/bin/bash

# I wrote this script to detect my T490 sensors and update the thinkfan
# config file. I know about that there are some form of support in the
# YAML format but the documenation is lacking and it's unclear exactly
# how it works ... so I rather do this my self.

# Fail if there is any error, this will result in an missing or invalid
# config file for thinkfan and it will keep the fan levels at a safe auto.
set -eu -o pipefail

rm /etc/thinkfan.conf || :

echo -e "\ntp_fan /proc/acpi/ibm/fan\n" > /etc/thinkfan.detect.conf

hwmon() {
    echo "# Sensor name $1" >> /etc/thinkfan.detect.conf
    echo -e "hwmon $2\n" >> /etc/thinkfan.detect.conf
}

# Scan sys for sensors
for sensor in $(find /sys/devices -type f -name "temp*_input"); do
    path="${sensor%/*}"
    input="${sensor##*/}"
    name="$(cat "$path/name")"

    case $name in
        coretemp)
	  hwmon $name $path/$input
	  ;;
        acpitz)
	  hwmon $name $path/$input
	  ;;
        iwlwifi)
	  hwmon $name $path/$input
	  ;;
        pch_*)
	  hwmon $name $path/$input
	  ;;
    esac
done

echo '
(0,	0,	70)
(1,	65,	75)
(2,	70,	80)
(3,	70,	85)
(4,	75,	87)
(5,	80,	90)
(7,	85,	32767)
' | cat /etc/thinkfan.detect.conf - > /etc/thinkfan.conf
