---

- hosts: all
  sudo: yes
  vars:
    debs:
    - { 
        url: "https://dl.bintray.com/mitchellh/vagrant/vagrant_1.6.5_x86_64.deb", 
        name: "vagrant_1.6.5_x86_64.deb",
        sha256sum: "e2c7af6d032ac551ebd6399265cb9cb64402c9fb96a12289161b7f67afada28a"
      }
    packages:
    - { 
        url: "https://dl.bintray.com/mitchellh/packer/0.5.2_linux_amd64.zip", 
        type: "zip", 
        name: "packer_0.5.2_linux_amd64.zip", 
        sha256sum: "813f856a3d326d2a65f561edac8050d981f93ea51da03b0fb6b3d72010a5fc96"
      }
  tasks:
  - name: Install software from repo
    apt: pkg={{ item }} state=present
    with_items:
    - vim
    - mercurial
    - git
    - terminator
    - chromium-browser
    - virtualbox
    - curl
    - sshpass
    - pandoc
  - name: Download debs
    get_url: url={{ item.url }} dest=/tmp/{{ item.name }} sha256sum="{{ item.sha256sum }}"
    with_items: debs
#  - name: Download packages
#    get_url: url={{ item.url }} dest=/tmp/{{ item.name }} sha256sum="{{ item.sha256sum }}"
#    with_items: packages
  - name: Install debs
    apt: deb=/tmp/{{ item.name }}
    with_items: debs
