---

- name: Clone pathogen.vim
  git:
    repo: "https://github.com/tpope/vim-pathogen.git"
    dest: "~/.vim/git/pathogen.vim"
    version: bd0c1abcce2acd46330c6edb15457f3f56677e5a # v2.3
    force: yes
- name: Install pathogen.vim
  command: mv ~/.vim/git/pathogen.vim/autoload/pathogen.vim ~/.vim/autoload/pathogen.vim creates="~/.vim/autoload/pathogen.vim"

- name: Clone plugins for Pathogen to manage
  git:
    repo: "{{ item.path }}"
    dest: "~/.vim/bundle/{{ item.name }}"
    version: "{{ item.version }}"
    force: yes
  with_items:
    - path: https://github.com/chase/vim-ansible-yaml.git
      name: vim-ansible-yaml
      version: 85bec55a1390e59c4fec3e79f961a95f77b30337
    - path: https://github.com/scrooloose/nerdtree.git
      name: nerdtree
      version: 205367ab3f46dcc88b6ebb819a276e793a21e995 # 4.2.0
    - path: https://github.com/kien/ctrlp.vim.git
      name: ctrlp
      version: c1646e3c28d75bcc834af4836f4c6e12296ba891 # 1.79
    - path: https://github.com/ekalinin/Dockerfile.vim.git
      name: Dockerfile.vim
      version: 1fc71e1c82e1b818d3353c8f1c28afece5e20046
    - path: https://github.com/tpope/vim-commentary.git
      name: vim-commentary
      version: v1.2
    - path: https://github.com/airblade/vim-gitgutter.git
      name: vim-gitgutter
      version: 339f8ba079ed7d465ca442c9032b36bc56c21f61
    - path: https://github.com/bling/vim-airline.git
      name: vim-airline
      version: v0.7

- name: Download plugins from vim.org to plugin
  get_url:
    url: "{{ item.url }} "
    dest: "~/.vim/plugin/{{ item.name }}"
  with_items:
    - url: "http://www.vim.org/scripts/download_script.php?src_id=13110"
      name: "rcs.vim"
      sha256sum: 76a67192026626cd3bc5903a441019ad5eb5eea1fada85ba6726a81ddcf87231

- name: Install packages from apt
  apt: name={{ item }}
  sudo: yes
  with_items:
    - vim-syntax-go

- name: Enable plugins managed with vim-addon-manager
  shell: vim-addon-manager -w install {{ item }}
  sudo: yes
  with_items:
    - go-syntax
