# vim: set expandtab ts=4 sw=4:

[ -z "$PS1" ] && return

BASHRC_PARTS=~/.config/bashrc

load_log() {
    echo -e $@ >> $BASHRC_PARTS/load.log
}

load_part() {
    local part=$1

    load_log "Load part: $part"
    . $part
}

# Load bash parts from $BASHRC_PARTS
load_log "\nBash shell $$ started at: $(date)"
for part in $BASHRC_PARTS/*.sh; do
    load_part $part
done
